name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UnitTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 拷贝 .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: 安装依赖
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: 生成 key
      run: |
        php artisan key:generate
        php artisan jwt:secret
    - name: 目录权限
      run: chmod -R 777 storage bootstrap/cache
    - name: 执行单元测试 (Unit and Feature tests) via PHPUnit
      env:
        APP_ENV: testing
        APP_DEBUG: true
        BCRYPT_ROUNDS: 4
        CACHE_DRIVER: array
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
        MAIL_MAILER: array
        QUEUE_CONNECTION: sync
        SESSION_DRIVER: array
        TELESCOPE_ENABLED: false
      run: php artisan test
